<Project Sdk="Microsoft.NET.Sdk">
  <!-- "NotesHandlers_Int/NotesHandlers_IntegrationTests.csproj" -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NotesDomain\NotesDomain.csproj" />
    <ProjectReference Include="..\NotesHandlers\NotesHandlers.csproj" />
    <ProjectReference Include="..\NotesStorage\NotesStorage.csproj" />
  </ItemGroup>

</Project>
