<Project Sdk="Microsoft.NET.Sdk.Web">
  <!-- NotesBackEnd project - The REST API layer -->
  <!-- File: "NotesBackEnd.cs" -->
  <!-- File: "NotesRestAPI.cs" -->
  <!-- File: "UsersRestAPI.cs" -->
  <!-- File: "appsettings.json" -->
  <!-- File: "appsettings.Development.json" -->
  <!-- File: "Properties/launchSettings.json" -->
  
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NotesDomain\NotesDomain.csproj" />
    <ProjectReference Include="..\NotesHandlers\NotesHandlers.csproj" />
    <ProjectReference Include="..\NotesStorage\NotesStorage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.22" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <!-- NotesBackEnd project - The REST API layer -->
</Project>
